version: '3'
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /var/www/react-app/node_modules
            - .:/var/www/react-app
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /var/www/react-app/node_modules
            - .:/var/www/react-app
        command: ["npm", "run", "test"]
